# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development CI PR

on:
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: package-lock.json Validation
      run: npm i --package-lock-only
    - name: Dependency Install
      run: npm ci
    - name: ESlint Action
      uses: sibiraj-s/action-eslint@v2
      with:
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
    - name: Build the App
      run: npm run build --if-present
      env:
          CI: false
    - name: Run Test Suite (specified in package.json)
      run: npm test
